### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by notangelmario** [solidjs/solid-router#116]
The documentation on this package is pretty bad. I mean I saw a lot of functions I could make use of, but I don't understand their code, and they are not documented. I saw almost no comments in the entire code. I would be glad to help with the documentation, but I would need some time and a starting point.

Also a question I have. How in the world do you go back to previous route? Am I forced to pass state on each route change?

**Comment by SalemCode8** [comment]
+1

I had to go through the code to know that NavLink has prop called `end`

**Comment by ryansolid** [comment]
This is a fair question and something we need to do better. Eventually taking it to a documentation site probably. PRs for docs improvements are always welcome. Right now it's just a Readme but we can build it out from there to a few md files and then a site as needed.

**Comment by ryansolid** [comment]
We now document the router in the official docs so I consider this done. Not that the documentation effort is done, but that we have a process now.
