### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by darklight9811** [solidjs/solid-router#124]
Hey, I'm starting to use SolidJS and wanted to help the community. Would like to know if you are interested in:
- adding history
- adding back
- templates for github (issues mainly)

I'm asking this before doing anything because I wouldn't want to waste time if this is not wanted/needed.

**Comment by ryansolid** [comment]
Thanks and sorry for the slow response. Focus has been elsewhere and my partner on the router has been busy with his new job on the Marko team. 

Templates for Issues? Yes.

Adding Back? Yeah I imagine so. If you mean API for like goBack?

Adding History? That's interesting and something that probably needs some thought. Can you expand on what you were thinking?

**Comment by lisonge** [comment]
How is it now?

**Comment by ryansolid** [comment]
Stale closing.
