### ISSUE TITLE
Scroll to section with id from a hashed url

### ISSUE THREAD

**Issue by SmartNetAR** [solidjs/solid-router#130]
### Describe the bug

It happened to me like in the issue 83 report https://github.com/solidjs/solid-app-router/issues/83 that luckily I solved it. Since I can scroll from the same page to the section with id. Eg `<section id="contact">...</section>` using Link or NavLink.
But the problem is when I load the page from a url in a new tab, for example localhost:3000/#contact or localhost:3000#contact, the scroll is always positioned at the top.
I appreciate if you can tell me if I'm doing something wrong.

### Your Example Website or App

https://digichanges.com/#about

### Steps to Reproduce the Bug or Issue

If you click on the links, you will see that it scrolls correctly

If you load the url in the browser you will see that it does not scroll to the corresponding section https://digichanges.com/#about

### Expected behavior

I would expect that when accessing the site, it would scroll to the section identified in the url after the #

### Platform

- OS: [macOS, Linux]
- Browser: [Chrome, Safari]

### Additional context

Without the router it worked fine.

**Comment by Brendan-csel** [comment]
I've been testing for this and believe it has improved in the latest versions - albeit still an issue with one case.

I've tested
- using a link/a to `#contact` with the same route - worked.
- refreshing a page with `#contact` in the url - worked.
- using a link from one route to another that includes `#contact`.  Weirdly that doesn't seem to work the first time - but then does scroll to `#contact` if going back to the original route and trying again.

The last case needs further investigation.

**Comment by ryansolid** [comment]
Looks like the reproduction doesn't use Solid anymore. So I can't reproduce currently. If this issue comes up again more than happy to look at it.
