### ISSUE TITLE
useRouteData should not unwrap function return type.

### ISSUE THREAD

**Issue by minht11** [solidjs/solid-router#146]
### Describe the bug

https://github.com/solidjs/solid-router/pull/138 After passing function as useRouteData type, it's return type is automatically unwrapped which is incorrect.

### Your Example Website or App

https://www.typescriptlang.org/play?jsx=0&ssl=8&ssc=7&pln=5&pc=1#code/PTAECUHsFcBcFMBOoDGkAm8BQsCeAHeUAWQENcAjeceWaRAOwBUD4AeJgPlAF5QnQ8AB4IG6AM6gAFADo5pRAHNxALlCkGuAJS9uASwYAzJBFAB+U2qZY0DcbFDRx1GAgAipWKV6gOnKTo83NBi8IYG8OjqkiEA1gyQAO4M0STkVDR0jCyEflhYIKAAqs7IaJg4rKAAgigo8OLikIh+PgG6-DaQdg7ont58Ti5w8B5ebLX1jc1sDNAAtlSInP5aWH1eAVhAA

### Steps to Reproduce the Bug or Issue

```tsx
// Data.ts
function UserData() {
  const [data] = createResource(() => number);
  return data;
}

// Component.ts
type Accessor<T> = () => T
const data = useRouteData<Accessor<number>>()
data() // TS error. This expression is not callable. Type 'Number' has no call signatures.
```

### Expected behavior

DataFunction usually returns Resource function and not its resolved value, so types should reflect that.

### Platform

- OS: All
- Browser: All
- Version: All

**Comment by minht11** [comment]
I just realised that the intention is to pass typeof DataFunc, which I find annoying in my case and bit unusual, but this is working as expected. Disregard this.

**Comment by ryansolid** [comment]
This is fair to bring up. Most of what drove that types decision is the convenience for SolidStart. Most solutions in that space let you do `typeof loader`. But this is a good point. I guess there isn't a way to easily support either?..

**Comment by ktnyt** [comment]
As a newcomer to TypeScript and SolidJS I apologize if my comment is not able to capture the full scope of how typing is handled in the SolidJS ecosystem.

I personally feel that automatically unwrapping the function return type here is counter-intuitive. The `userData` function from the example provided in #138 returns an untyped object literal, which should be explicitly denoted in `useRouteData` with `ReturnType` as that's what's being intended: *specifying the return type of a function that returns an anonymous type*. If using `ReturnType` is unwanted the type in question should probably be declared explicity:

```ts
type User = { id: number; name: string };
function userData(): Resource<User> {
  const [user] = createResource(async () => ({ id: 123, name: "hello" }));
  return user;
}

const user = useRouteData<Resource<User>>();
```
