### ISSUE TITLE
`preventDefault` not working when using it inside `Suspense`

### ISSUE THREAD

**Issue by Supertigerr** [solidjs/solid-router#159]
### Describe the bug

I don't know if this issue is related to solid router or solid, but when using `event.preventDefault()` for the child element click event inside the `Link` tag, while also using `Suspense` and `Lazy`, when clicking on the child element, The browser will still redirect. This does not happen if I don't use `Suspense` and `Lazy`.

Working fine without `Suspense`: https://stackblitz.com/edit/github-imhxsg-f6uejd?file=src%2FApp.tsx
Not working with `Suspense`: https://stackblitz.com/edit/github-imhxsg-x4nwkq?file=src%2FApp.tsx,src%2FHome.tsx

### Steps to Reproduce the Bug or Issue

1. Open the first link, click on `Do Nothing`, It does not redirect you, which is intended and is working fine.
2. Open the second link, which has `Suspense`, do the same thing as step 1, It WILL redirect even with the `event.preventDefault()`.

### Expected behavior

It should not redirect when using `Suspense` and `Lazy`

### Platform

- OS: Windows
- Browser: Chrome
- Version: 104

**Comment by ryansolid** [comment]
Fixed in `@solidjs/router` v0.4.3
