### ISSUE TITLE
Catch-all not working with dynamic route

### ISSUE THREAD

**Issue by DominicTobias** [solidjs/solid-router#172]
### Describe the bug

Hi, I'm trying to have a catch all inside a dynamic route but unknown routes that have at least one segment are not being caught, instead they are hitting the `<Navigate>` route:

```tsx
import { Routes, Route, Navigate } from 'solid-app-router'
import { Editor, NotFound } from 'src/pages'

export function App() {
  return (
    <Routes>
      <Route path="/:lang">
        <Route path="/" element={<Editor />} />
        <Route path="/*any" element={<NotFound />} />
      </Route>
      <Route path="/*">
        <Navigate href="/en" />
      </Route>
    </Routes>
  )
}
```

I expect `/en/doesnt-exist` to hit `<NotFound>`. I thought it might be that the outer catch-all takes precedence but moving it to the outer route doesn't help:

```tsx
export function App() {
  return (
    <Routes>
      <Route path="/:lang">
        <Route path="/" element={<Editor />} />
      </Route>
      <Route path="/:lang/*any" element={<NotFound />} />
      <Route path="/*">
        <Navigate href="/en" />
      </Route>
    </Routes>
  )
}
```

Not sure if this is a misunderstanding or a bug 🤔 Thanks!

**Note the `<Navigate>` redirect doesn't work in StackBlitz but does if you download the project. You can still see it rendering `<Editor>` though as if it had.**

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-vsxmh3

### Steps to Reproduce the Bug or Issue

1. Navigate to `/en/doesnt-exist`
2. It hits the `<Navigate>` redirect route and ends up at `/en/` (the `<Editor>`)

### Expected behavior

Should load the `<NotFound>` route

### Platform

- OS: macOS
- Browser: Chrome
- Version: 105

**Comment by ryansolid** [comment]
THis was a docs error.. 

It should be:
```js
export function App() {
  return (
    <Routes>
      <Route path="/:lang">
        <Route path="/" element={<Editor />} />
      </Route>
      <Route path="/:lang/*any" element={<NotFound />} />
      <Route path="/*" element={<Navigate href="/en" />} />
    </Routes>
  )
}
```
Children will eager eval.. it should be in the `element` prop.
