### ISSUE TITLE
Freshly created solidjs project does not build.

### ISSUE THREAD

**Issue by timbasel** [solidjs/solid-router#187]
### Describe the bug

I'm trying to build a fresh solidjs project with the `@solidjs/router`.
But the build fails with the following error: 
```
[solid] /home/timbasel/Projects/.tmp/solid-test/node_modules/@solidjs/router/dist/components.jsx: transformCondition is not defined
file: /home/timbasel/Projects/.tmp/solid-test/node_modules/@solidjs/router/dist/components.jsx
error during build:
ReferenceError: /home/timbasel/Projects/.tmp/solid-test/node_modules/@solidjs/router/dist/components.jsx: transformCondition is not defined
    at /home/timbasel/Projects/.tmp/solid-test/node_modules/babel-plugin-jsx-dom-expressions/index.js:1463:26
    at Array.forEach (<anonymous>)
    ...
```

The error is reproducible on Stackblitz so I don't think it is a local configuration issue. From what I can tell , it is not directly a `solid-router` issue, but originates from the solid build pipeline.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-qbckbq

### Steps to Reproduce the Bug or Issue

1. `npx degit solidjs/templates/js my-app`
2. `cd my-app`
3. `npm i`
4. `npm i @solidjs/router`
5. Import the router in the project, e.g. change `index.tsx` and wrap `<App />` with `<Router>`
6. `npm run dev`

### Expected behavior

Successful build.

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Package Manager: [npm, yarn]

**Comment by timothyallan** [comment]
Our existing project just stopped working after the upgrade this morning with the identical error after upgrading to solid 1.6. `npm install solid-js@1.5.9` fixes it.

**Comment by ryansolid** [comment]
Should be fixed in the latest. babel-preset-solid. I was missing a testing a code path that was missing an import.

Might need to blow out your lockfiles to get the latest.
