### ISSUE TITLE
transformCondition is not defined

### ISSUE THREAD

**Issue by henry-cotton** [solidjs/solid-router#188]
### Describe the bug

Trying to build an old React app in Solid, but trying to build anything that imports from @solidjs/router gives the error
"..\node_modules\@solidjs\router\dist\components.jsx: transformCondition is not defined".

Even with a simple App component like this:
`
render(
	() => (
		<Router>
			<div></div>
		</Router>
	),
	document.getElementById("root")
);
`

I've used the old version, solid-app-router, at version 0.3.3, but upgrading to 0.5.0 gives me this error.
I don't understand what's gone wrong, since this error doesn't appear in forums or in the docs.

### Your Example Website or App

https://github.com/Dynamic-Array/fathom-solid-analyser

### Steps to Reproduce the Bug or Issue

- Create a new Solid app
- Install the latest @solidjs/router
- Try & run a vite dev environment with any @solidjs/router components imported

### Expected behavior

I should load the single-page component. There should be no navigation, and all URLs will load a simple div.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 0.5.0

**Comment by Brendan-csel** [comment]
I just did the following and it seemed to work okay....

```
npx degit solidjs/templates/ts-router my-app
```
Update `package.json` to current latest versions...
```
  "devDependencies": {
    "vite": "^3.1.8",
    "vite-plugin-solid": "^2.3.10",
    "vite-plugin-windicss": "^1.8.8"
  },
  "dependencies": {
    "@solidjs/router": "^0.5.0",
    "solid-js": "^1.6.0"
  }
```
then
```
pnpm i
pnpm run dev
```

Are you still seeing errors in your project?

**Comment by ryansolid** [comment]
I fixed this, this morning. Others have confirmed. Fresh install or blowing out lock files should get the latest for the babel plugin.
