### ISSUE TITLE
useSearchParams values don't track granularly

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-router#196]
### Describe the bug

Params aren't independently trackable causing anything depending on it to fire. According to @rturnq:

> They should be independent but there could be a bug here. The implementation is a kind of memoized proxy map thing which maybe has been affected by changes to Solid.

### Your Example Website or App

None

### Steps to Reproduce the Bug or Issue

Sample code:
```ts
  const [params, setParams] = useSearchParams<{
    collection: string;
    category: string;
  }>();

createEffect(() => console.log(params.category));
createEffect(() => console.log(params.collection));

setParams({ 'collection': 'testing' });

// Output: both category and collection log when just `collection` is updated
```

### Expected behavior

Should track granularly.

### Platform

Solid 1.6.1 using SolidStart  0.2.3

**Comment by Brendan-csel** [comment]
I copied the relevant bits from the router internals to [the playground](https://playground.solidjs.com/?hash=1986484479&version=1.4.1).

In summary it looks like the params _should_ work independently - so hopefully not hard to fix.  I'll keep looking.

**Comment by Brendan-csel** [comment]
I assume you're calling `setParams` a little differently to your example above?  

Maybe like `setParams({ collection: "1", testing: "2"})`

**Comment by Brendan-csel** [comment]
So I tried with this code in an application and it seems to behave correctly - effects logged independantly when either `collection` or `category` changed.

```js
  const [params, setParams] = useSearchParams<{
    collection: string;
    category: string;
  }>();
  
  createEffect(() => console.log("category:", params.category));
  createEffect(() => console.log("collection", params.collection));

  setParams({collection: "a"})
  setParams({category: "1"})
  setParams({collection: "b", test:"foo"})
  setParams({collection: "c", category: undefined})
```

I might be missing the bug sorry.

**Comment by davedbase** [comment]
@Brendan-csel I thumbed through the setParams example. Just corrected it, sorry for the mistake.

You may be right because I just isolated the test in a separate codebase and it's not triggering the resources I'm tracking the param on. When I dug a bit deeper into my implementation it seems like the issue was related to `useIsRouting()` being triggered which made it seem like the resource was the culprit.

I suppose my next question is: should param cause the `useIsRouting()` signal to change? Can it technically be considered a route change if the path itself doesn't change?

I'll close this out for now b/c it's not a bug but just something to mention.
