### ISSUE TITLE
Version 0.5.0 is missing the #182 fix

### ISSUE THREAD

**Issue by timbasel** [solidjs/solid-router#199]
### Describe the bug

The 0.5.0 version (default on `npm`) is missing the small fix (#182) that was applied to the master branch (0.4.3). For me this bug leads to the `activeClass` rules not being correctly applied on initial load. 

### Your Example Website or App

https://github.com/solidjs/solid-router

### Steps to Reproduce the Bug or Issue

1. Create a new solid project with @solidjs/router
2. Add a Link with some `activeClass`
3. `activeClass` is not applied on initial page load

### Expected behavior

Have all fixes applied to the latest version of @solidjs/router

### Platform

- OS: Arch Linux
- Browser: Firefox 106.0.5

**Comment by jochim-vd** [comment]
I am also facing this problem, and the same goes for `inactiveClass`.

**Comment by timbasel** [comment]
@ryansolid Could you please take a look at this. I would make a PR, but I'm unsure to which branch to make the change to.

**Comment by ryansolid** [comment]
Yeah just published 0.5.1 with the fix.
