### ISSUE TITLE
'A' element doesn't scroll non-root elements

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-router#217]
### Describe the bug

"A" elements don't scroll if the scrolling area is not the entire page.

Say I've got a documentation site with a navigation sidebar, and a main section that has the actual documentation (much like the Solid-Start doc site). Clicking on an 'A' link navigates to the new page, but doesn't scroll the document panel to the top. This means that the user is on a new page, but scrolled to the bottom, which is annoying behavior. Note that the current solid-start doc site suffers from the same issue.

If I change the 'A' element to a lower case 'a' (so that it does a full page reload) it of course works as expected, albeit more slowly.

Adding 'noScroll=false' has no effect.

I suspect that the problem is because the doc panel isn't scrolling the entire page, only a nested panel within the page.

(I'm just going to paste in the link to solid-start's doc page, since it exhibits the same problem as my app.)

### Your Example Website or App

https://start.solidjs.com

### Steps to Reproduce the Bug or Issue

1. Go to [soli](https://start.solidjs.com)
2. Go to any page that is taller than the screen.
3. Scroll down to the bottom.
4. Now, using the nav on the left side, go to a different page.

The page is scrolled down, and the top of the page is obscured.

### Expected behavior

When navigating to a new page, the embedded panes should scroll to the top, or to the anchor tag if one is present in the URL.

### Platform

- OS: any
- Browser: Edge

**Comment by Brendan-csel** [comment]
The router just does ` window.scrollTo(0, 0)`.

It doesn't know anything about other containers you may have with scrollable content.

Two possible options:
- arrange your css so your main content is the window content (and only the sidebars are fixed position)
- add an `onMount` handler to explicitly scroll to the top of your custom scrollable container.

**Comment by viridia** [comment]
All right. Actually, I had to do something slightly different, because my doc page is a single component that has an <Outlet />, so it doesn't mount when the page changes.

Instead, I created an effect which reacts to a change in the location (via useLocation()).

**Comment by Brendan-csel** [comment]
Thanks for the update @viridia.  If you're happy with that, could you please close this issue?

**Comment by viridia** [comment]
Closed, but do bear in mind that the solid-start doc site suffers from the same issue and will need a similar fix.
