### ISSUE TITLE
Tricky interactions between Suspense, Navigate, and createResource()

### ISSUE THREAD

**Issue by SenojLuap** [solidjs/solid-router#219]
### Describe the bug

So, I'm trying to make a landing page that will fetch some data, then automatically send the user to the correct route based on that data.

My attempt looks like this:
```javascript
export default async function Landing() {
  const [firstVersion] = createResource(async () => {
    const versions = await fetch(`${RunEnv.apiUrl}v1/versions`)
      .then((response) => response.json())
      .then((versions) => versions.map((version) => version.replace(".", "_")));
    return versions[0];
  });
  return (
    <div>
      <Suspense fallback="Please hold. Your call is important to us...">
        <Navigate href={`/${firstVersion()}`} />
      </Suspense>
    </div>
  );
}
```

However, this creates a kind of race condition. Based on how I *think* this works, the Navigate element needs to be constructed before Solid sees the signal get fired, so that Suspense knows what to render. But, because of how Navigate works, it redirects the user as soon as it's created.

Is there a better way to handle this?

### Your Example Website or App

http://donthaveone.com

### Steps to Reproduce the Bug or Issue

I'm *pretty* sure this component will have the same affect/result. It's the same as my example above, just dropped in JsonPlaceholder for data

```javascript
export default async function Landing() {
  const [firstId] = createResource(async () => {
    const versions = await fetch("https://jsonplaceholder.typicode.com/todos")
      .then((response) => response.json())
    return versions[0].userId;
  });
  return (
    <div>
      <Suspense fallback="Please hold. Your call is important to us...">
        <Navigate href={`/${firstId()}`} />
      </Suspense>
    </div>
  );
}
```

### Expected behavior

As described above, I'd like to fetch data *before* the Navigate component kicks on

### Platform

- OS: Linux
- Browser: Firefox
- Version:
    - SolidJS 1.5.1
    - @solidjs/router 0.5.1

**Comment by Brendan-csel** [comment]
Could you do something like... 
```js
export default async function Landing() {
  const navigate = useNavigate()
  await fetch(`${RunEnv.apiUrl}v1/versions`)
    .then((response) => response.json())
    .then((versions) => navigate(`/${versions[0].replace(".", "_")}`));

  return (
    <div>
      Please hold. Your call is important to us...
    </div>
  );
}
```

Unsure if you are server-side rendering or if you want to do the fetch server-side.  If so may be able to still do similar within the createResource fetcher, or create an effect that waits for the resource result to come in and then calls `navigate`.

Probably need to handle the error case too (like if fetch fails).

**Comment by SenojLuap** [comment]
Hmm, on paper it looks like it should work. I'm unable to test immediately, but when I do, I'll come back and report how it went.

**Comment by SenojLuap** [comment]
Well, the code as written results in a console warning of:
"Unrecognized value. Skipped inserting 
Promise { <state>: "pending" }
dev.js:433:17"
But, that seems like a silly fix I can deal with. Beyond that it is working as intended! Thanks a bunch!

**Comment by Brendan-csel** [comment]
DId you spot my chance to the code sample above yesterday?  I change the function definition to not be async and removed the await.  That should resolve your warning.
