### ISSUE TITLE
Documentation on '.' (period/dot) in routes

### ISSUE THREAD

**Issue by SenojLuap** [solidjs/solid-router#221]
### Describe the bug

Not really a bug, as I'm pretty sure this is working as intended, but I learned through trial and error that routes (at least dynamic routes) don't behave well when a '.' (dot/period) is part of the name/parameter. Navigating *to* those routes via Navigate or A will work correctly, but direct links will not (coming from an external site, for example).

After thinking about it, I realize that's probably known/intended behavior, but it would have been helpful for me if that was indicated in the documentation.

### Your Example Website or App

http://donthaveone.com

### Steps to Reproduce the Bug or Issue

n/a

### Expected behavior

n/a

### Platform

n/a

**Comment by Brendan-csel** [comment]
Do you still see this issue in `0.6.0`?

**Comment by ryansolid** [comment]
Closing as stale (no reproduction).
