### ISSUE TITLE
Solid Router doesn't handle history.state correctly when using <A>

### ISSUE THREAD

**Issue by pauloevpr** [solidjs/solid-router#223]
When passing history state to `<A>` like this:

```jsx
<A href={link()} state={sate()}>
```

the state is not available in the destination page/component. Calling `history.state` in the destination component's setup function or even within `onMount` will always return `undefined`. This seems to happen because `@solidjs/router` calls `history.pushState` after everything else in the navigation workflow happens. 

I would imagine that updating the history would ideally be the very first step in the navigation workflow. This is to be consistent with the back/forward navigation triggered by `popstate` where the history is the very first thing to be updated. If the history is always updated first, then `history.state` will consistently be available to the page.

**Comment by ryansolid** [comment]
The answer is to use `useLocation` state instead of browsers to observe transitions. I believe this is working. In any case this issues has gone stale.
