### ISSUE TITLE
Click on <a> tag does not reliably scroll to section

### ISSUE THREAD

**Issue by me-jterhorst** [solidjs/solid-router#229]
### Describe the bug

I set up a small website, that is supposed to work like a single page application.
My main nav consists of 4 links of which the first is an <A> Tag and the other three are regular <a> with hashes as hrefs. 

The <a> Tags link to sections on my page and clicking on them should scroll the associated area into view, 
however, when I am clicking on a link on a desktop browser I notice that sometimes the link will just become unresponsive and the page won't move at all unless I clicked it a few times or click to another link first and then the original one again. 

On first load it seems to work reliably initially except for the furthest section. But once a link has been clicked and I scroll up to click the same link again, it will stop working unless I click the link up to 6 times.

On Mobile I have the same nav hidden behind a toggle, but so far I couldn't reproduce the problem there. 

In my opinion it's worth mentioning that I tried to get around this problem by overwriting the default click behaviour of an <a> Tag with an eventListener. I thought that document.getElementById("id").scrollIntoView() would give me the desired behaviour programmatically. But instead I got the same problem. 

At another issue I saw that someone with a similiar problem suggested using target="_self" on the link but that did not fix my issue. 

### Your Example Website or App

https://logopaedie-langenberg.com/

### Steps to Reproduce the Bug or Issue

1. Go to the Web Page [https://logopaedie-langenberg.com/](https://logopaedie-langenberg.com/)
2. Click on either "Über mich", "Anfragen", "Verordnungen
3. If it scrolls to the associated section, go back up and click the same link again.

### Expected behavior

As a User I expect to click the link and directly get to the desired information.

### Platform

- OS: [ Windows 11]
- Browser: [Edge(Chromium), Firefox]
- Version: ["@solidjs/router": "^0.6.0", "solid": "^0.2.1", "solid-js": "^1.6.6"]

**Comment by siduck** [comment]
@me-jterhorst  did you manage to fix it?

**Comment by fabiospampinato** [comment]
I think that's just how the browser works, the fragment technically didn't change, so no navigation happened, so the browser doesn't scroll to the element again.

**Comment by ryansolid** [comment]
We've made some changes since this issue was posted. Although I suspect it may still be here. But the reproduction is fine so since this is stale I'm going to close. OP can re-open with a reproduction, and anyone else a new issue if they hit something like this.
