### ISSUE TITLE
Data function doesn't re-run

### ISSUE THREAD

**Issue by dkonasov** [solidjs/solid-router#232]
### Describe the bug

I have a dynamic route with some param in url, that contains link to the same route, but with another param value (account route with the links to another accounts). But when I am navigating with this link, my data function that resolves account details doesn't re-run, and data doesn't actually update.

### Your Example Website or App

https://codesandbox.io/p/github/dkonasov/solidjs-router-bug-demo/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cld3go43t000e8shzd6w4gmpc%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cld3go69x00153c5qs2yqig9z%2522%253A%257B%2522key%2522%253A%2522cld3go69x00153c5qs2yqig9z%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522cld3gw7q3000t3c5qknt2tsvz%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cld3goa9b006y3c5q033wjngz%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cld3go8pf00563c5qso0e3zd3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cld3go69x00153c5qs2yqig9z%2522%252C%2522spacesOrder%2522%253A%255B%2522cld3go69x00153c5qs2yqig9z%2522%255D%257D

### Steps to Reproduce the Bug or Issue

1. Click on "List"
2. Click on "Entity 1"
3. Click on "Entity 2"

### Expected behavior

Data function re-runs, and entity id becomes incremented by 1.

### Screenshots or Videos

Data-function doesn't re-runs, and data is not updated.

### Platform

- OS: macOS
- Browser: Safari
- Version: 15.1
- Node: 18.12.0
- solid-js: 1.6.9
- @solidjs/router: 0.6.0

**Comment by ryansolid** [comment]
The way this works is that the parameters are reactive. The routeData doesn't run again. The expectation is that you create signals/resources in here that read from that reactive data. If that example was to work you need to return the whole params object and then access `.id` under a reactive primitive or the JSX. Basically making it the same as `useParams`. But as I said generally you are going to create a resource that reads the param in its first argument. Like the example here: https://github.com/solidjs/solid-router#data-functions
