### ISSUE TITLE
Hydration error when using streaming, `lazy` imports, and createResource

### ISSUE THREAD

**Issue by marbemac** [solidjs/solid-router#233]
### Describe the bug

When using `renderToStream` + lazy imports, suspended content, driven by a resource, sometimes disappears with a hydration error.

TBH I wasn't sure whether to open this issue here or in the core solid repo, but it seems that without the router involved the issue goes away (see the https://github.com/marbemac/solid-streaming-lazy-bug/tree/no-router branch).

BTW since downstream projects such as `solid-start` leveraging lazy + resource + solid-router, folks that turn on streaming there might end up seeing this issue as well.

### Your Example Website or App

https://github.com/marbemac/solid-streaming-lazy-bug

### Steps to Reproduce the Bug or Issue

1. `git clone https://github.com/marbemac/solid-streaming-lazy-bug`
2. `pnpm i`
3. `pnpm dev`
4. Open `http://localhost:5173/lazy`
5. Open devtools, set network throttling to 3g so that there is some latency loading the lazy imported route component
6. Reload the page

### Expected behavior

I should not see the hydration error / disappearing content.

### Screenshots or Videos

You'll see that just after the resource finishes loading, and renders the list, the list disappears and the hydration key error logs in the console.

![2023-01-23 14 45 12](https://user-images.githubusercontent.com/847542/214134933-8ec49bdd-bcc4-4bc4-ad2b-9b9f40d6847f.gif)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
I have to admit this is an odd one.. I can reproduce it on first refresh but never again. Making it really hard to debug into. Thanks for reporting.

**Comment by ryansolid** [comment]
Ok.. I think this is fixed in the latest version of the libraries. I don't know what caused it before I'm afraid but there have been a decent amount of updates to the router and solid itself in the last year and a half. 

Here is the stackblitz with the updates. https://stackblitz.com/edit/github-r6khxx?file=package.json,src%2FRoot.tsx,src%2FApp.tsx,src%2Froutes%2Fnot-lazy.tsx

I hope that helps.
