### ISSUE TITLE
ESM "type": "module" / TS "moduleResolution": "nodenext" not working correctly

### ISSUE THREAD

**Issue by ChristianKaeser** [solidjs/solid-router#238]
### Describe the bug

When trying to use solid-router in a Node project with ESM-type module resolution ("type": "module" and tsconfig "moduleResolution": "node16"/"nodenext"), instead of the default CommonJS one, TypeScript will complain about imports without file extension inside solid-router's `components.d.ts`, `index.d.ts`, `integration.d.ts`, `lifecycle.d.ts`, `routing.js` and `utils.d.ts`.

_Note_
In the example stackblitz link https://stackblitz.com/edit/typescript-kgzvck?file=index.ts&view=editor I first need to go to `tsconfig.json` and press CTRL + s for saving/installing/setting up TS to show the error inside index.ts

### Your Example Website or App

https://stackblitz.com/edit/typescript-kgzvck?file=index.ts&view=editor

### Steps to Reproduce the Bug or Issue

1. Create a basic TypeScript project with solidjs
2. In `package.json`, set `"type": "module"`
3. In `tsconfig.json`, set "moduleResolution": "nodenext" or "node16"
4. Install solid-router dependency in project
5. When importing, observe the TypeScript errors in solid-router's .d.ts files regarding `"./..."` `import`s/`export`s without ".js" file extension

### Expected behavior

Just like solidjs itself, solid-router should work in a ESM environment, not just the default CommonJS one, and TypeScript should not complain about these kinds of disallowed import declarations.

When patching all the offending imports in the above-mentioned files, everything works as it should.

### Platform

- Node v18.12.1
- tsc 4.9.4

**Comment by ChristianKaeser** [comment]
With this patch the issues are resolved for me: https://pastebin.com/2WTuJ2SV

**Comment by sachaw** [comment]
For ESM compliance, all imports require file extensions (`.ts` > `.js`, `.tsx` > `.jsx` etc)

**Comment by frank-weindel** [comment]
I wouldn't mind working on this. My experience has been that modern libraries work best when they use `moduleResolution` "Node16" in their tsconfig.json files. This allows TypeScript to enforce that the `.js` extensions are present. Would that be OK here? @ryansolid @rturnq

**Comment by ryansolid** [comment]
Closed by #363
