### ISSUE TITLE
<Switch> fails when getSearchParams initial value is undefined

### ISSUE THREAD

**Issue by timothyallan** [solidjs/solid-router#239]
### Describe the bug

When using getSearchParams.value as a `when` in `<Switch>`, if that value doesn't exist initially, but then is populated, `<Switch>` crashes.

I've got some tabs of various sections. Clicking a tab sets the search param to the string value of the index. i.e. mypage.html?section=2

if the page is loaded without the `?section=xxx`, and the tabs are switched, `<Switch>` dies.

### Your Example Website or App

dont have a stackblitz acct :|

### Steps to Reproduce the Bug or Issue

To replicate,add this to any page, then click the button to add the search param:

```
  const [getSearchParams, setSearchParams] = useSearchParams<{ section: string }>();
      
....


      <button onClick={() => setSearchParams({ section: '1' })}>Click</button>
      <Switch>
        <Match when={getSearchParams.section === '0'}>
          <div>0</div>
        </Match>

        <Match when={getSearchParams.section === '1'}>
          <div>1</div>
        </Match>

        <Match when={getSearchParams.section === '2'}>
          <div>2</div>
        </Match>
      </Switch>
```

### Expected behavior

I'd expect to be able to use the `<Switch>` component with search params, regardless of their initial value.

### Platform

macOS, Windows, Linux
Browser: all

"solid-start": "^0.2.19"

**Comment by julian-barker** [comment]
I'm not able to replicate the error. Pasting that code into a bare solid-start project (^0.2.19) and loading the root path on localhost, I'm able to press the button and have the correct div appear.

**Comment by timothyallan** [comment]
Hmm okay, must be a project related issue. Will see if I can get a simple repro case up somewhere and report back.

**Comment by timothyallan** [comment]
I had also wrapped the`<Switch>` with `<Transition>` from `solid-transition-group` in the project, and while that does still generate an error when you click the button using the code above, it's an error from the transition component, and not the same error I was getting in the project. Will re-open if I can replicate the router/solid error!
