### ISSUE TITLE
useSearchParams uses decoded URI

### ISSUE THREAD

**Issue by Yukaru-san** [solidjs/solid-router#241]
### Describe the bug

The _useSearchParams_ hook's _setSearchParams_ will decode any given URL. 

This means that the encoded versions of symbols like ? or # will be decoded upon usage.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-y1upyl?file=src/SearchParamIssue.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Stackblitz
2. Open the issue page
3. Spectate as the URL changes from _%23world_ to _#world_

### Expected behavior

Expected behavior would be:
 Route: /search/0/%23world 
 setSearchParams( { p: "1" } );
 Result: /search/0/%23world?p=1

Actual behavior is:
 Route: /search/0/%23world 
 setSearchParams( { p: "1" } );
 Result: /search/0/#world?p=1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Brendan-csel** [comment]
I believe this was resolved from `0.6.0` onwards (late December).  Does upgrading resolve this for you?

**Comment by Yukaru-san** [comment]
Upgrading did solve my issue. I wonder why my 'npm outdated' didn't catch this one...  Whatever, thanks for the help!
