### ISSUE TITLE
[Feature]: Memory integration

### ISSUE THREAD

**Issue by gabrielelpidio** [solidjs/solid-router#244]
At the time, Solid-router doesn't have a memory integration like [react-router](https://github.com/remix-run/react-router) or [tanstack-router](https://github.com/tanstack/router) do. Memory integration is handy when trying to embed routing logic inside a snippet for an otherwise fully static website like a Shopify theme (my case) or when trying to manage routing logic without affecting the URL of the page.

I'm currently using the exposed `createIntegration` function with a custom `createMemoryHistory` heavily inspired by both [react-router](https://github.com/remix-run/react-router/blob/682810ca929d0e3c64a76f8d6e465196b7a2ac58/packages/router/history.ts#L227) and [@tanstack/react-router](https://github.com/TanStack/router/blob/2abd72ed3828d577db22dc2622b54aded1ec4035/packages/router/src/history.ts#L197) to achieve this. I'm not sure if this is the best way to do it, but it works for me. I'm happy to submit a PR if you see this as a good addition to the library. I'm also happy to hear any feedback on how to improve this.

I'm gonna leave the code here for reference:

```ts
type Listener = (value: string) => void;

export const createMemoryHistory = () => {
  const entries = ["/"];
  let index = 0;
  const listeners: Listener[] = [];

  const go = (n: number) => {
    // https://github.com/remix-run/react-router/blob/682810ca929d0e3c64a76f8d6e465196b7a2ac58/packages/router/history.ts#L245
    index = Math.max(0, Math.min(index + n, entries.length - 1));

    const value = entries[index];
    listeners.forEach((listener) => listener(value));
  };

  return {
    get: () => entries[index],
    set: ({ value, scroll, replace }: LocationChange) => {
      if (replace) {
        entries[index] = value;
      } else {
        entries.splice(index + 1, entries.length - index, value);
        index++;
      }
      if (scroll) {
        scrollToHash(value.split("#")[1] || "", true);
      }
    },
    back: () => {
      go(-1);
    },
    forward: () => {
      go(1);
    },
    go,
    listen: (listener: (value: string) => void) => {
      listeners.push(listener);
      return () => {
        const index = listeners.indexOf(listener);
        listeners.splice(index, 1);
      };
    },
  };
};

export const memoryIntegration = () => {
  const memoryHistory = createMemoryHistory();
  return createIntegration(
    memoryHistory.get,
    memoryHistory.set,
    memoryHistory.listen,
    {
      go: memoryHistory.go,
    }
  );
};
```

**Comment by ryansolid** [comment]
Yeah this seems pretty reasonable. Would welcome a PR.
