### ISSUE TITLE
Adding deployment guidelines to the readme.

### ISSUE THREAD

**Issue by bramdoppen** [solidjs/solid-router#269]
When deploying my Solid.js client-side rendered app to Vercel, the routing didn't work. 
There was nothing clear specified in the readme. Scrolling through the issues I found this post and looking at it, it's obvious that you would need something like this to work on Vercel.

Would it be an idea to provide a small guideline for the popular platforms (Vercel, Netlify, AWS, etc) with tips like these?

```json
{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}
```

_Originally posted by @tbdsux in https://github.com/solidjs/solid-router/issues/63#issuecomment-999696986_

**Comment by ryansolid** [comment]
Probably, I haven't seen this in other router docs, probably because it is specific to each platform. But maybe a section where we mention it is needed in deployed environments and then give like a Netlify and Vercel example would be sufficient.
