### ISSUE TITLE
useBeforeLeave not firing on history.back()

### ISSUE THREAD

**Issue by KamehamehaNudel** [solidjs/solid-router#277]
### Describe the bug

The "useBeforeLeave" hook seems to only be firing when navigating using links.
When using the browsers back/forth buttons it does not appear to execute.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-ejhtft?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

1. Go to the "test" route using the nav link.
2. Go back to the "home" routeusing the nav link.
3. An alert "here" will show up
4. Go back to the "test" route using the nav link.
5. Click the "back" button (fires history.back())
6. The route changes correctly, but the alert does not show up 

### Expected behavior

As a user i expeted the "useBeforeLeave" function to also fire when using the "back" button (either progromatically or with the actual browser buttons in a 'real' environment).
I am in both cases leaving the current route so I don't see why it shouln't execute.

### Platform

- OS: Windows
- Browser: Firefox
- Version: 114.0.2 (64-Bit)

**Comment by Brendan-csel** [comment]
The [PR that added useBeforeLeave](https://github.com/solidjs/solid-router/pull/186) only supports router-initiated blocking.  Not browser-initiated blocking such as back/forward buttons.

I do have a [fork of this router](https://github.com/cselnz/solid-router/tree/publish) were I had a go at adding those other blockers.  We have been using that in production and it seems to be working fine - but hasn't had broader testing.  Also we us the Hash Integration so "normal" integration hasn't been tested.  I think [this is the commit](https://github.com/solidjs/solid-router/commit/51b050403462225a2997d10c87d1a97073027d57) that adds that ability.

**Comment by KamehamehaNudel** [comment]
Aye i See. Thanks for the quick answer, I'll see if i can get that running as a custom integration or patch.
Will that also make it to main version (eventually) ?
Or is it 'intentional' afterall?

**Comment by Brendan-csel** [comment]
I just happened update that branch of mine recently so if you want to quickly test with it you can try install `csel-solid-router` from npm and find/replace to update any files that import the router.

> Will that also make it to main version (eventually) ? Or is it 'intentional' afterall?

That'll be up to @ryansolid.  It is quite a bit of code - although it "works for me".

**Comment by CreativeTechGuy** [comment]
I just want to chime in that I found this issue because this is something that I was very surprised was missing. Hopefully it can get added!

**Comment by ryansolid** [comment]
@Brendan-csel I'm open to looking at getting this in. If you have a PR I'd review it.

**Comment by ryansolid** [comment]
Closed by #363

**Comment by grobitto** [comment]
Still bug for me - useBeforeLeave not triggering on back, also not triggering on useNavigate()(-1)
"@solidjs/router": "^0.15.3",

**Comment by dennev** [comment]
@grobitto Can the usage examples in this post help?

**Comment by dennev** [comment]
@grobitto Can the usage examples in this post(#533) help?
