### ISSUE TITLE
`useRouteData` return wrong type

### ISSUE THREAD

**Issue by denbon05** [solidjs/solid-router#281]
### Describe the bug

`block.data.ts`
```ts
export const BlockData: RouteDataFunc = ({
  params,
}: RouteDataFuncArgs): Resource<ETHBlock> => {
  const [block] = createResource(Number(params.id), fetchBlock);
  return block;
};
```

`BlockMore.tsx`
```ts
const BlockMore: Component = () => {
  const block = useRouteData<ETHBlock>();
  // const block = useRouteData<Resource<ETHBlock>>(); // doesn't work
  // const block = useRouteData() as unknown as Resource<ETHBlock>; // works
  return <div>{JSON.stringify(block(), null, 2)}</div>; // in fact it's callable
/*                             ^^^
This expression is not callable.
  Type 'Block' has no call signatures.ts
*/
};

export default BlockMore;
```

### Your Example Website or App

https://github.com/denbon05/blockexplorer/blob/main/src/pages/BlockAbout.tsx

### Steps to Reproduce the Bug or Issue

https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router#data-functions
Follow the documentation to face this bug.

### Expected behavior

The router data function should infer the appropriate type. 

### Screenshots or Videos

Called `block` result in browser:
![image](https://github.com/solidjs/solid-router/assets/58662935/3389358f-c090-4310-a099-dcfca2df2e1d)

### Platform

- OS: Linux
- Browser: Chrome, Brave
- Version: "@solidjs/router": "^0.8.2",

**Comment by ryansolid** [comment]
It is supposed to be the type of the RouteData function which I admit in this case isn't very convenient but is more so in file system routed systems.

Ex.
```js
import type { BlockData } from "./block.data.ts"

const BlockMore: Component = () => {
  const block = useRouteData<typeof BlockData>();
  return <div>{JSON.stringify(block(), null, 2)}</div>; // in fact it's callable
};

export default BlockMore;
```

**Comment by denbon05** [comment]
@ryansolid in that case I'm facing `'block()' is of type 'unknown'`
it seems we still have to use `as` like here:
```ts
const blockSrc = useRouteData<typeof BlockData>() as Resource<ETHBlock>;
```

**Comment by ryansolid** [comment]
This is related to the previous version of the router. TS issues with `useRouteData` was one of the motivations of changing it. Closing as addressing any bug here is no longer planned.
