### ISSUE TITLE
Scroll bug in SolidStart HN demo

### ISSUE THREAD

**Issue by redbar0n** [solidjs/solid-router#283]
**Why:**

A small nitpicky bug, but which gives a bad impression of SolidStart.
I don't think it's a bug in SolidStart, more likely a bug in the HN demo,
but it's hard to tell. Viewers may conclude it's a bug in SolidStart, which
would give an unnecessary bad impression.

**Reproduce:**

1. Go to https://solid-hackernews-edge.netlify.app/ or https://solid-start-hn.netlify.app/
2. Click into comments of first post
3. Scroll down
4. Click browser back button

**Effect:**

The header of the post flashes briefly before you get back to the main page.

**Cause:**

It scrolls to the top, before going to the previous page.

**Expected result:**

Go directly back to main page. Then set the scoll position.

**Comment by ryansolid** [comment]
I don't know if it is back caching or update to transition timing but I don't reproduce this anymore. I tried with slow network and slow CPU (x20) and I don't see it.
