### ISSUE TITLE
Cannot export parts of '@solidjs/router'

### ISSUE THREAD

**Issue by KevinBLT** [solidjs/solid-router#286]
### Describe the bug

Simply when I do:
```js
export { A, Route, Routes, Outlet } from '@solidjs/router';
```

The application will not build (ssr) and fail with:
```bash
file:///node_modules/@solidjs/router/dist/index.js:1
import { isServer, delegateEvents, createComponent as createComponent$1, spread, mergeProps as mergeProps$1, template } from 'solid-js/web';
                                                                                                             ^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'template'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
```

Looks like some of the magic generated code breaks after build.

E.g. @solidjs/meta doesn't have this problem.

Any idea? Or am I missing something?

### Your Example Website or App

Code above

### Steps to Reproduce the Bug or Issue

Use the code above in I file in a vite ssr build.

### Expected behavior

Export these components

### Platform

- OS: MacOS
- @solidjs/router 0.8.2

**Comment by ryansolid** [comment]
This looks like it is pulling in the client version of Solid on the server. For SSR we don't actually ship different versions of the library, because the client build is different too.. Instead we recommend using `solid` export condition which pulls in the source. Our Vite plugin should be setting that automatically. But that is where I'd start my search.

**Comment by KevinBLT** [comment]
I might have an idea, what to change maybe. Still I don't understand why it's only the router and none of the other packages? Wouldn't that affect all of them equally?

**Comment by ryansolid** [comment]
Closing as stale. I'd need a concrete example to look at this more.

**Comment by iwt-narendervaddepelly** [comment]
Why some components weren't exposed or do they replaced? 

> Module '"@solidjs/router"' has no exported member 'Outlet'
> Module '"@solidjs/router"' has no exported member 'useRoutes'

**Comment by md-owes** [comment]
@ryansolid, i upgraded all frontend libraries in my application and suddenly there are issues related to Outlet and RouteDataFuncArgs. I have downgraded @solidjs/router to 0.9.1 as there is no clear documentation with examples to execute this migration. Would really appreciate if there is a clear migration path for breaking changes.
