### ISSUE TITLE
additional option to `<A>` for top menus?

### ISSUE THREAD

**Issue by mathieuprog** [solidjs/solid-router#299]
Say a top menu Wallets:
```jsx
<A class={styles.link} href={getRoute(/* ... */)} onClick={handleClick}>
  Wallets
</A>
```
Link:
> href="/organization/dc70c79c-5c09-4de4-8728-8e82cb3884e6/wallets"

The page rendered is a list of wallets. When clicking on a wallet, the location becomes:
> /organization/dc70c79c-5c09-4de4-8728-8e82cb3884e6/wallets/ff2605f4-1f50-4de7-a3a0-ecd4fc4843bd

It would be nice to have an additional option e.g. a boolean `top`, which allows to activate the menu when the href starts with the current location.

There's already an option `end` but surprisingly it does kinda the opposite, it checks whether the current location starts with href. By the way this also made me wonder, for what kind of pages is `end` useful?

**Comment by ryansolid** [comment]
Oh that is odd. I thought end was was to force exact matches because say a link to `/` would always be active otherwise by default.

**Comment by mathieuprog** [comment]
Sorry Ryan, I misread the docs for option `end`.
> If true, only considers the link to be active when the curent location matches the href exactly; if false, check if the current location starts with href

The suggestion still stands: how about an additional option (eg `top`), that allows to match a route if it the current location starts with that route. For example:
route = /wallets
current location = /wallets/32
=> match

I'm thinking about top menus. If no such option, how could that be handled?

**Comment by mathieuprog** [comment]
Sorry Ryan, misread the doc and all is fine now. I do not understand the naming `end`, I agree with this person:
https://github.com/solidjs/solid-router/pull/179#issuecomment-1272236181

Thank you so much for your reply <3
