### ISSUE TITLE
The new version of ruoting is not working

### ISSUE THREAD

**Issue by TheElegantCoding** [solidjs/solid-router#313]
### Describe the bug

i am not using default import for my components maybe that is the error but i have this and nothing show, no error in console 

```jsx
import { HomePage } from '@module/home/page/home_page';
import { MarketingAdsPage } from '@module/home/page/marketing_ads_page';
import { homeRouterPath } from '@module/home/router/home_router_path';
import { Route, Router } from '@solidjs/router';

import type { JSX } from 'solid-js';

const App = (): JSX.Element => (
  <Router>
    <Route
      component={HomePage}
      path={homeRouterPath.home}
    />
    <Route
      component={MarketingAdsPage}
      path={homeRouterPath.marketingAds}
    />
  </Router>
);

export { App };
```

My home page

```jsx
const HomePage = (): JSX.Element => (
  <>
    <header>
      <Navbar />
      <Principal />
    </header>
    <PrincipalSlider />
    <main>
      <AboutUs />
      <SectionService />
      <SectionContact />
      <SectionGoodbye />
    </main>
    <footer>
      <Footer />
      <FooterCopyright />
    </footer>
  </>
);

export { HomePage };
```

My marketing ads page

```jsx
import type { JSX } from 'solid-js';

const MarketingAdsPage = (): JSX.Element => (
  <div />
);

export { MarketingAdsPage };
```

i dont think this is stable i will dump to 0.9.0 version i need to finish this website today

### Your Example Website or App

i will added if needed

### Steps to Reproduce the Bug or Issue

create the elements

### Expected behavior

show the page and the components, or and error, no error and nothing is in the screen

### Platform

- OS: Windows
- Browser: Opera
- Version: 0.1.0.0, solid-js 1.8.7

**Comment by ryansolid** [comment]
Can I get a reproduction? I've converted about a dozen examples so far and haven't hit any issues like this. The core routing logic hasn't changed with his release. If there is an issue I imagine it is in the top level wiring that I can't see in completion from the example code. I have several examples that are more or less simple like this that work no problem.

**Comment by Brendan-csel** [comment]
Just noting, I've also just completed updating one of our apps to router version `0.10.1` and it is working fine.  This app has 300 routes and also includes a nested `<HashRouter>`.  Client-side rendering only though.  

Aside: migrating was trivial.  The only bit that felt awkward was moving everything surrounding our `Route`s to be inside the router's `root` property.

**Comment by TheElegantCoding** [comment]
sorry I made the reproduction and I found maybe it was an error in how i structured the router i can't say what the mistake was, but `0.10.1` works well
