### ISSUE TITLE
[Documentation] README example incorrect? 

### ISSUE THREAD

**Issue by aalmazan** [solidjs/solid-router#315]
### Describe the bug

https://github.com/solidjs/solid-router/blob/898174ee1b86e005d1e006ebbb4cf4953e614dc2/README.md?plain=1#L418-L438

Confused with the code snippet above. Is there another function `deleteUser` (or `deleteTodo`) that we need to know of or are all the function references supposed to point to a single function?

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. Visit https://github.com/solidjs/solid-router/blob/898174ee1b86e005d1e006ebbb4cf4953e614dc2/README.md?plain=1#L418-L438 to check affected lines

### Expected behavior

Maybe more clarity on what actions is doing 

### Platform

Any

**Comment by ryansolid** [comment]
Thanks.. my bad from missing a reference.
