### ISSUE TITLE
Behavior of anchor tag on v0.10.x

### ISSUE THREAD

**Issue by hugomcm** [solidjs/solid-router#319]
### Describe the bug

When migrating to v0.10.x, realized that the achor tag `<a>` doesn't have the same behavior as on v0.9.x. It's not doing a server call as expected. Seems like <a> is just working as `<A>`.
For example, I was counting on a GET request `<a href="/logout">Logout</a>` to do a logout on the server.

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Create and click an `<a>` tag

### Expected behavior

Expected `<a>` tag to do a server call

### Platform

- OS: Linux
- Browser: Chromium
- Version: 119.0.6045.199

**Comment by Brendan-csel** [comment]
Try `<a href="/logout" target="_self">Logout</a>` or see `explicitLinks` in README
