### ISSUE TITLE
"@solidjs/router": "^0.10.3" not working

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid-router#323]
### Describe the bug

- folowing https://github.com/solidjs/solid-router?tab=readme-ov-file#getting-started
- url path and showing components not working

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-myqh2h?file=src%2Findex.tsx

### Steps to Reproduce the Bug or Issue

- just open stackblitz 

### Expected behavior

just working like "@solidjs/router": "^0.9.1"

### Platform

- OS: Windows
- Browser: Chrome
- Version: [120]

**Comment by Brendan-csel** [comment]
It looks like your links and routes didn't match and you (were rendering twice).

It seems to work after adding some more links and routes and match up (and removing one of the render calls)

https://stackblitz.com/edit/solidjs-templates-gdqlqp?file=src%2FApp.tsx,src%2Findex.tsx

**Comment by sysmat** [comment]
Hm, very strange this new router(in my app when migrating to new router can not figure it out what is wrong), no errors but just dosen't show components, for me this is downgrade

**Comment by sysmat** [comment]
is there any debug or trace mode for this new router?

**Comment by sysmat** [comment]
I thinx I figure it out, before I was using a lot of Outlets and the new way is to wrapp it in a  function with childrens
