### ISSUE TITLE
BeforeLeaveEventArgs.retry with Router.base navigates to incorrect location

### ISSUE THREAD

**Issue by vveisard** [solidjs/solid-router#337]
### Describe the bug

When using the `base` prop on the `Router` component, invoking `BeforeLeaveEventArgs.retry` within `useBeforeLeave`  navigates to an incorrect location.

### Your Example Website or App

https://stackblitz.com/~/github.com/vveisard/bug-solidjs-router-base-with-use-before-leave

### Steps to Reproduce the Bug or Issue

1. install dependencies
2. Run "dev" package.json script
3. Navigate to https://localhost:3000/base
4. Click "to /bar" button
5. Observe resolved url to be /base/base/bar

(I recommend opening the StackBlitz preview in new tab, because you can see the resolved location much easier.)

### Expected behavior

As a user, I expected `BeforeLeaveEventArgs.retry` to navigate to the proper location (ie, same as Navigator).

### Platform

- OS: Manjaro Linux
- Browser: Brave
- Engine: pnpm, Bun 
- Version: Latest

**Comment by Brendan-csel** [comment]
Thanks for the great reproduction.  I've submitted a PR for a fix that seems to resolve this.
