### ISSUE TITLE
Data reconcilation for cached functions works incorrectly under some conditions

### ISSUE THREAD

**Issue by elite174** [solidjs/solid-router#343]
### Describe the bug

On the first cache revalidation, data is reconciled incorrectly, which causes rerenders. 

Example:
https://playground.solidjs.com/anonymous/b6b25440-9d66-467e-94ee-5148484a5bc2

You'll see in the console that items are rerendered on the first revalidation, however it doesn't happen when you continue revalidate the data.

### Your Example Website or App

https://playground.solidjs.com/anonymous/b6b25440-9d66-467e-94ee-5148484a5bc2

### Steps to Reproduce the Bug or Issue

Check out the example

### Expected behavior

Items should be reconciled correctly without rerenders

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
Thanks.. I missed this. I'm trying to track this one down but its odd.. Somehow on first load we aren't getting the wrapped value.
