### ISSUE TITLE
Typing fails to detect data prop type

### ISSUE THREAD

**Issue by staadecker** [solidjs/solid-router#344]
### Describe the bug

The current type setup requires a lot of extra code. Specifically in the following example I need to
1.  cast the component using `as Component` and

2. I need to check that `props.data` is not undefined even though it cannot be (afaik).

```javascript
// App.tsx
const fetchData = async () => {
  await new Promise((resolve) => setTimeout(resolve, 5000));
  return 'Fetched the data!';
};

const loadData = () => {
  const [res] = createResource(fetchData);
  return res;
};

const App: Component = () => {
  return (
    <Router>
      <Route path="/" component={HomePage as Component} load={loadData} /> // 👈 Casting shouldn't be needed
    </Router>
  );
};
```

```javascript
// HomePage.tsx
export const HomePage = (props: RouteSectionProps<Resource<string>>) => {
  if (props.data === undefined) { // 👈 This shouldn't be needed...
    throw Error('Something unexected happened!');
  }

  return <Suspense fallback={<p>Loading...</p>}>{props.data()}</Suspense>;
};
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-ssnat2?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Remove the `as Component` and observe how typescript throws an error
2. Or remove the `props.data === undefined` if statement and observe how typescript throws an erro

### Expected behavior

Neither should be needed

### Platform

- OS: Windows
- Browser: Firefox
- Version: 0.10.5

**Comment by staadecker** [comment]
PR #345 fixes issue 1. here but not number 2.

**Comment by Brendan-csel** [comment]
`props.data` will be `undefined` unless your route's `load` function happens to return something.

**Comment by staadecker** [comment]
> `props.data` will be `undefined` unless your route's `load` function happens to return something.

aha gotcha. I imagine it would be tricky (or completely impossible) to encode that logic in the typescript type system.
