### ISSUE TITLE
Form action set as insecure by google chrome.

### ISSUE THREAD

**Issue by AlbertSabate** [solidjs/solid-router#349]
### Describe the bug

When accessing a website with https, the forms action="" that are not https:// are set as insecure by Google Chrome [Google Chrome Docs](https://blog.chromium.org/2020/08/protecting-google-chrome-users-from.html).

The new form action on @solidjs/router renders the markup like this:
```{html}
<form method="post" action="action:signUpForm">...</form>
```

Google Chrome sets it as insecure, as shown in the image below.
<img width="787" alt="Screenshot 2024-01-04 at 11 04 24 PM" src="https://github.com/solidjs/solid-router/assets/2384218/ed86c3a1-628f-4e2c-8df7-bac683342d1d">

### Your Example Website or App

https://start.solidjs.com/core-concepts/actions#using-forms-to-submit-data

### Steps to Reproduce the Bug or Issue

Create a form using the example on the solidjs/start a website.
Open the site using https.
Click on any input, and the message will show.

### Expected behavior

The form should not be set as insecure as it could generate distrust from the users.

### Platform

Google Chrome.

**Comment by ryansolid** [comment]
Alright 0.10.7 is released
