### ISSUE TITLE
actionRef.startsWith is not a function

### ISSUE THREAD

**Issue by knpwrs** [solidjs/solid-router#357]
### Describe the bug

In `handleFormSubmit` it appears that somehow `evt.target.action` is an `HTMLButtonElement`, rather than a string.

### Your Example Website or App

https://gitlab.com/letschurch/lets.church/-/tree/web-solid-next/apps/web-solid-next?ref_type=heads

### Steps to Reproduce the Bug or Issue

Using the `action` function as your `action` with `method` set to `'post'` can somehow cause `evt.target.action` to be a button rather than a string, and the call to `startsWith` fails.

### Expected behavior

Using the `action` function as `action` with `method` set to `post` should always work.

### Screenshots or Videos

<img width="564" alt="image" src="https://github.com/solidjs/solid-router/assets/174864/3bb21857-5ff8-44d4-82d0-d0bcba80b8bf">

<img width="730" alt="image" src="https://github.com/solidjs/solid-router/assets/174864/60155db6-af40-4156-b371-08e8514599bd">

<img width="572" alt="image" src="https://github.com/solidjs/solid-router/assets/174864/30120352-685f-422f-9aeb-7d73f478a940">

### Platform

- OS: macOS
- Browser: Firefox
- Version: 121

### Additional context

I don't really know how this is happening. I would expect `.action` on an `HTMLFormElement` to always be a string (or undefined?) but it's a button. In this case, as you can see in the screenshot above, using `.getAttribute` returns the right value.

I have other forms that are working just fine, I don't know what's going on with this particular form.

**Comment by knpwrs** [comment]
Wait a minute, I recognize this bug. It happens when there is a field with `name` set to `action`. I feel like I submitted a PR to fix this in the older solid start but I couldn't find that PR.

**Comment by knpwrs** [comment]
In any case, #358 fixes it.

**Comment by ryansolid** [comment]
Hmm.. I think there was a reason I wanted to use the property because of the way it resolved path. But I understand the problem. Any fix will need to be tested thoroughly.
