### ISSUE TITLE
[Bug?]: Parameters don't get filled in on the loader in the routes

### ISSUE THREAD

**Issue by gabrielmfern** [solidjs/solid-router#381]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When trying to receive the parameters from the route inside of the `load` function for the `route` export of a route
the parameters come out as empty. Not sure if this was a `@solidjs/router` issue or a `start` issue, so I'm assuming this is
a start issue.

This can clearly be seen by just running the [hacker-news example](https://github.com/solidjs/solid-start/tree/main/examples/hackernews) and opening up [one of the stories](http://localhost:3000/stories/39403189).

### Expected behavior 🤔

That the parameters properly are passed in the `load` function defined in the `export const route = { ... }` statement.

### Steps to reproduce 🕹

Steps:

1. Add a `console.log` of the `params` inside of the `load` function here
   https://github.com/solidjs/solid-start/blob/b0428cb03e58dc3e98ec82c8193fd13709a1fb94/examples/hackernews/src/routes/stories/%5Bid%5D.tsx#L6-L10
2. Open the browser at http://localhost:3000/stories/39403189
3. Verify in the server logs that the parameters are just `{}` instead of the expected JSON `{ "id": "39403189" }`

### Context 🔦

I'm just trying to cache something the same as the hacker-news example does it, but in my situation it going on like this made it crash as my website wasn't ready to fetch on the client. I understand this is not how I should probably go about implementing this, and I am adding the proper code to handle the fetching on the client, but the load function should come with the proper parameters and this is still a bug.

### Your environment 🌎

```shell
Using the latest version of both the router and start.
```

Running this on Linux with Node 20.10.0

**Comment by ryansolid** [comment]
Yeah I think this is just platform to platform. We added `ownKeys` and set descriptors to configurable and enumerable. I'm not sure there is much more to be done. Just how proxies `console.log` I guess.
