### ISSUE TITLE
How do I listen for changes to `location.pathname`.

### ISSUE THREAD

**Issue by zhengyongkai** [solidjs/solid-router#386]
### Describe the bug

How do I listen for changes to `location.pathname`.

I want to make a breadcrumb, but I need to listen for current route changes, is this any good?

### Your Example Website or App

empty

### Steps to Reproduce the Bug or Issue

1. How do I listen for changes to `location.pathname`.

### Expected behavior

`createEffect` listens for changes to `location.pathname` or other methods, just like `useEffect` in `React` listens for `location.pathname`.

### Platform

- Solid-js ^1.8.14
- @solidjs/router ^0.12.3

**Comment by Brendan-csel** [comment]
See `useLocation` in the [README](https://github.com/solidjs/solid-router?tab=readme-ov-file#uselocation)

**Comment by zhengyongkai** [comment]
> See `useLocation` in the [README](https://github.com/solidjs/solid-router?tab=readme-ov-file#uselocation)


Thank you!
He did it!

```js
const location = useLocation();
const pathname = createMemo(() => location.pathname);
createEffect(() => console.log(pathname()));
```

**Comment by zhengyongkai** [comment]
Another issue

From `xx?id=1` to `xx?id=2`

How should I monitor the change? I've used `useParams` and `useSearchParams` but neither of them can monitor the change.

**Comment by ryansolid** [comment]
@chiefcll is reactive. The advice given above is correct. You may have encountered a bug. Maybe something was introduced by the navigation refactor a couple versions back. Feel free to write a report with reproduction.
