### ISSUE TITLE
Slow performance matching route with localeCompare

### ISSUE THREAD

**Issue by chiefcll** [solidjs/solid-router#406]
### Describe the bug

Matching a segment is taking ~45 ms due to localeCompare. This only happens when deep linking - the base route doesn't have an issue.

<img width="406" alt="image" src="https://github.com/solidjs/solid-router/assets/2090941/5c69dccd-10a3-4297-8d6f-bc56f73fb419">

### Your Example Website or App

https://lightning-js.github.io/solid-demo-app/#/browse/movie

### Steps to Reproduce the Bug or Issue

Load up the site with 6x slowdown in Chrome - doing the initial match for a route takes ~45ms.

<img width="378" alt="image" src="https://github.com/solidjs/solid-router/assets/2090941/82cbb1bb-1eab-4845-87e6-1d14b60adb6d">

### Expected behavior

Much faster matching of routes. 
https://stackoverflow.com/questions/14677060/400x-sorting-speedup-by-switching-a-localecompareb-to-ab-1ab10
Recommend not using localeCompare

### Platform

Mac, Chrome, latest

**Comment by ryansolid** [comment]
I'd definitely be open to this. Have you tried this switch yourself in your app?

**Comment by chiefcll** [comment]
I haven't tried changing it yet. I assume using normal string comparison is much faster - but some users may need localeCompare. Probably need an option to use one or the other based on if the user needs it - but I assume large percentage of users don't need localeCompare for routing.
