### ISSUE TITLE
Why not just export useRouter and useRoute?

### ISSUE THREAD

**Issue by zxdstyle** [solidjs/solid-router#408]
### Describe the bug

I have no way to get the info assigned to the current route when it was defined.For example, I want to get the value of the following route definition checkAuth

```
const routes: RouteDefinition[] = [
    {
        path: '/home',
        component: lazy(() => import('@/views/home')),
        info: {
            checkAuth: true,
        },
    },
]
```

### Your Example Website or App

empty

### Steps to Reproduce the Bug or Issue

empty

### Expected behavior

empty

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
Yeah we should. I'm surprised a bit we haven't.

**Comment by ryansolid** [comment]
I've updated the readme with an example using `useCurrentMatches`
