### ISSUE TITLE
location.state undefined with HashRouter on v0.13.3

### ISSUE THREAD

**Issue by pecoram** [solidjs/solid-router#416]
### Describe the bug

With version 0.13.3 of solid-router the set location.state is undefined using HashRouting .

### Your Example Website or App

https://codesandbox.io/p/sandbox/solid-router-state-issue-nfp7dg

### Steps to Reproduce the Bug or Issue

1) On _pageone_ page
```
    const navigate = useNavigate();
    navigagate("newpage", { state: { myState: true }}
```
2) On _newpage_ page
```
     const location = useLocation();
     console.log(location.state.myState)
```

3) location.state is undefined

### Expected behavior

I expected location.state is { myState: true } but got undefined.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.13.3

### Additional context

In v0.13.2 it works

**Comment by oedotme** [comment]
@pecoram Here's a [StackBlitz example with `location.state` changes](https://stackblitz.com/edit/solid-router-back-forward-state-change) as expected.

Could you please share an example with your usage if your issue persist? Thanks

**Comment by oedotme** [comment]
@pecoram For some reason, none of the CodeSandbox links worked for me.

I've found that this issue happens only with `replace: false` (the default option) and added a [potential fix](https://github.com/solidjs/solid-router/pull/417) for that.

**Comment by pecoram** [comment]
In the meantime, I have corrected the two links
