### ISSUE TITLE
In the new version, Route is imported as a type rather than a method.

### ISSUE THREAD

**Issue by cppsh1t** [solidjs/solid-router#434]
### Describe the bug

I've set up a new Solid project and then installed the latest version of the router(0.13.4). Although the router is functioning properly, within vscode, Route is being imported as a type instead of a method.
Then, I downgraded the router's version to 0.13.3, restarted vscode, and everything worked as expected. 

### Your Example Website or App

sry, i don't have

### Steps to Reproduce the Bug or Issue

1. pnpm create solid
2. pnpm add @solidjs/router
3. pnpm install
4. use Router and Route

### Expected behavior

no error in vscode

### Screenshots or Videos

<img width="543" alt="error1" src="https://github.com/solidjs/solid-router/assets/127290659/2591db5c-ad2f-40eb-8567-b579de67bd51">
<img width="321" alt="error2" src="https://github.com/solidjs/solid-router/assets/127290659/9d6681ab-5062-4d9b-815d-01283b9d07a2">

### Platform

- OS: Windows
- Browser: Edge

**Comment by jpdutoit** [comment]
I think this is due to my change #432 

It should export both, lemme check...

**Comment by jsimonrichard** [comment]
Created an reproduction repo before I saw this issue. Here it is in case it helps: https://github.com/jsimonrichard/solid-router-0.13.4-route-type-error-mre

**Comment by mdddj** [comment]
Same question
