### ISSUE TITLE
ErrorBoundary fallback renders twice

### ISSUE THREAD

**Issue by andreiborza** [solidjs/solid-router#440]
### Describe the bug

The ErrorBoundary fallback component renders twice when using solid router and navigating to a route that has an ErrorBoundary with an error.

### Your Example Website or App

https://codesandbox.io/p/devbox/nameless-forest-45lzdm?file=%2Fsrc%2Findex.tsx%3A11%2C35

### Steps to Reproduce the Bug or Issue

1. Open console
2. Click on the `Go to error` link

### Expected behavior

Error should only be logged out once but is logged out twice.

### Screenshots or Videos

https://github.com/solidjs/solid-router/assets/168741329/d40bd7a8-fed9-4fce-abdd-4a64dc8645ef

### Platform

- OS: macOS
- Browser: Chrome
- Version: [e.g. 91.1]

### Additional context

Possibly related to: https://github.com/solidjs/solid/issues/1586

**Comment by ryansolid** [comment]
Looks like issue is also closed by https://github.com/solidjs/solid-router/pull/442

**Comment by andreiborza** [comment]
Can confirm, it's fixed!
