### ISSUE TITLE
0.14 breaks FormData file serialisation

### ISSUE THREAD

**Issue by plushdohn** [solidjs/solid-router#469]
### Describe the bug

Version 0.14 and above seems to have broken file uploads done via a server action's `formData` argument. `File`s on a Node server get serialised and look like an `[object File]` instead of an actual `File` so it's impossible to get the underlying buffer anymore.

This single commit https://github.com/solidjs/solid-router/commit/bd9f19a19a07f1484a1bc87f1660495c7a816f0a seems to be causing the bug as undoing those precise changes fixes the issue.

### Your Example Website or App

https://stackblitz.com/~/github.com/plushdohn/solid-start/tree/plushdohn/repro-formdata?file=examples/basic/src/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Create a `<form>` that uses a server action from the router and has a file input
2. Do a `formData.get("file")` on the server and console.log the output
3. Revert to 0.13.6 to fix the bug

### Expected behavior

I know there are limitations in file upload via `FormData` but I'd expect the default behaviour to work

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.14.1

### Additional context

**Comment by plushdohn** [comment]
I'd gladly make a PR but I don't have context on why the initial change was made.

**Comment by katywings** [comment]
I think your form just misses the `enctype="multipart/form-data"` attribute for file uploads. Before 0.14 all forms where implicitly sent with this attribute which was inconsistent with the html standard 😅.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype
Goes into more detail about this

**Comment by plushdohn** [comment]
> I think your form just misses the `enctype="multipart/form-data"` attribute for file uploads. Before 0.14 all forms where implicitly sent with this attribute which was inconsistent with the html standard 😅.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype Goes into more detail about this

TIL about `enctype`, cheers!
