### ISSUE TITLE
[Bug] Incorrect Redirection Behavior with Nested Routes in Solid Router

### ISSUE THREAD

**Issue by zobweyt** [solidjs/solid-router#472]
### Describe the bug

I've encountered a strange behavior when using nested routes in my Solid Start application. Specifically, when I added an additional routes group and nested an authenticated route within it, the application started redirecting me to the login page instead of the expected home page ("/") after logging out.

As @Brendonovich mentioned in [Discord](https://discord.com/channels/722131463138705510/1273976366999666801):
- It seems that `$isAuthenticated` may be becoming `false` before the redirect completes, causing the application to redirect back to the login page.
- When an *unauthenticated user* navigates from `/` to `/settings` it logs `"<Authenticated />"`, and then `/settings` → `/login` [redication happens](https://github.com/zobweyt/solid-start-auth-example/blob/fa3430acc26fde170b7a827c15f0c47762331d70/src/routes/(group)/(authenticated).tsx#L29-L33) but `"<Authenticated /> cleanup"` **doesn't get called**. Then, after pusing the "Login" button, `/login` to `/settings` [redirection happens](https://github.com/zobweyt/solid-start-auth-example/blob/fa3430acc26fde170b7a827c15f0c47762331d70/src/lib/auth/actions.ts#L13C1-L13C36) and `"<Authenticated />"` gets logged, then on logout `"<Authenticated /> cleanup"` gets called.
- There appears to be a lingering reactive state (`<Switch />`/<`Match />` still hanging around and being reactive) in the Solid Router that does not clean up properly after logging out, leading to unexpected behavior.

Also, try removing the `/(group)` folder and the `(group).tsx` and move everything to the root of the `/routes` folder. There **won't** be such behavior.

### Your Example Website or App

https://github.com/zobweyt/solid-start-auth-example

### Steps to Reproduce the Bug or Issue

0. *Ensure you're logged out and refreshed the page.*
1. Navigate to the `/about` or `/settings` route (protected). *It will redirect you to the `/login` route as you're not authenticated.*
2. Log in with any credentials.
3. Navigate to the `/settings` route (protected). *It won't redirect you now as you're authenticated now.*
4. Push the "Logout" button on the `/settings` page.
5. **Observe the incorrect redirect behavior:**
   1. Redirects to `/` first.
   2. Redirects to `/login?redirect=%2F` **(unexpected)**.

### Expected behavior

After logging out, it should redirect only to `/` and then not to `/login`.

##### Video with steps to reproduce
https://github.com/user-attachments/assets/50684c90-c610-438e-90ba-f01fb212ab65

##### Missing console log
![image](https://github.com/user-attachments/assets/3a393176-07cf-49a0-b389-25dd846aa4c7)

#### Expected behavior

Note, this is true when you'll remove the `/(group)` folder and the `(group).tsx` and move everything to the root of the `/routes` folder.

https://github.com/user-attachments/assets/2bbcfc98-914c-4ca1-88b2-490aef7f6738

![image](https://github.com/user-attachments/assets/6af8b220-2f4e-406f-8a45-b3bf32b2be83)

### Platform

- **OS:** Microsoft Windows [Version `10.0.22621.4037`]
- **Browser:** Google Chrome [Version `127.0.6533.120`]

### Additional context

A common use case for implementing such groups is in scenarios where there is a sidebar navigation for an index page that is accessible to all users, regardless of their authentication status. Additionally, for protected routes, the sidebar should be also present, but it should not be displayed for such routes as `/login` or `/register`.

### Related Issues
- https://github.com/solidjs/solid-router/issues/247
- https://github.com/solidjs/solid-router/discussions/364

**Comment by ryansolid** [comment]
Interesting.. This only seems to happen under a very specific set of steps. It is vital that you login on a page that was a redirect to the `/settings` page for this to happen. And I think that is where the bug is. It happens before we ever log in. There is a stranded `/settings` page. Why is interesting. I will look into it.

**Comment by ryansolid** [comment]
Yeah this is a bug in disposal in the core of Solid. I will take a look.

**Comment by ryansolid** [comment]
This should be released in 1.8.23 of solid-js
