### ISSUE TITLE
Document path pattern syntax

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid-router#67]
It looks like the syntax supported for path patterns is the same as React Router, but it'd be helpful to at least say "supports `:param` and `*rest` parameters", and perhaps for those unfamiliar, clarify that `:param` matches a single component between slashes, while `*` must be the final thing (and looking at the code, I think prefixed by a slash?).

I found this hard to figure out without reading the code, because you also mention Ember Router which I'm not familiar with, so I figured there might be some additional pattern syntax.

Admittedly I couldn't find this well documented in React Router either, but I found brief mention [here](https://reactrouter.com/docs/en/v6/getting-started/concepts#definitions) and [here](https://reactrouter.com/docs/en/v6/api#generatepath).

**Comment by ryansolid** [comment]
We have added some docs [here](https://github.com/solidjs/solid-router#dynamic-routes). Until we get official docs site I think this one is good for now.
