### ISSUE TITLE
does not provide an export named 'Routes'

### ISSUE THREAD

**Issue by rooflesia** [solidjs/solid-router#76]
Uncaught SyntaxError: The requested module '/node_modules/solid-app-router/dist/index.jsx' does not provide an export named 'Routes', any solution?

**Comment by ryansolid** [comment]
Hmm.. that's unusual as it's definitely there.

Could it be attempting to pull it into a CJS environment? Some build setups require named exports need to be explicitly set. What bundler are you using?

**Comment by PatrickLumenus** [comment]
I am having the same problem. Except, for me it is saying "The requested module '/node_modules/solid-app-router/dist/index.jsx' does not provide an export named 'effect'". I am using Rollup to compile a CJS SSR app.

**Comment by ryansolid** [comment]
Closing as stale.. No other reports of this and would need more information or reproduction.
